// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Svz.Common;

namespace Svz.Common.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20190120121807_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Svz.Common.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Authors");

                    b.Property<string>("Category")
                        .HasMaxLength(255);

                    b.Property<string>("Cover")
                        .HasMaxLength(255);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000);

                    b.Property<string>("Ean")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<decimal>("FormatHeightCm");

                    b.Property<decimal>("FormatWidthCm");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsInStock");

                    b.Property<string>("Isbn")
                        .HasMaxLength(30);

                    b.Property<short>("PagesCount");

                    b.Property<string>("Publisher")
                        .HasMaxLength(255);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<short>("YearPublished");

                    b.HasKey("BookId");

                    b.ToTable("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
